"""Serialized live-session state and durable, at-most-once report attempts.

No Discord or Hermes imports: a transport provides trusted events and delivery.
"""

import hashlib
import re

from .commands import CommandRequest, handle_command


class LiveSession:
    def __init__(self, engine):
        self.engine = engine
        self.store = engine.store
        self.config = engine.config
        with self.store.transaction():
            version = self.store.get_setting("transport_schema_version", 1)
            if version != 1:
                raise ValueError("Unsupported transport schema")
            self.store.db.execute("CREATE TABLE IF NOT EXISTS deliveries("
                                  "report_id TEXT PRIMARY KEY REFERENCES reports(id) ON DELETE CASCADE,"
                                  "message_id TEXT, outcome TEXT NOT NULL, updated_at REAL NOT NULL)")
            self.store.db.execute("CREATE TABLE IF NOT EXISTS command_receipts("
                                  "message_id TEXT PRIMARY KEY, created_at REAL NOT NULL)")
            self.store.set_setting("transport_schema_version", 1)
            # A crashed process may have sent successfully before saving the response.
            self.store.db.execute("UPDATE reports SET status='uncertain' WHERE status='sending'")
            self.store.db.execute("UPDATE deliveries SET outcome='uncertain' WHERE outcome='sending'")

    def gap(self, reason):
        if reason not in {"startup", "disconnect", "reconnect", "queue_full", "unavailable_edit",
                          "deleted_message", "invalid_event", "worker_failure"}:
            raise ValueError("Unknown coverage gap")
        now = self.engine._now()
        with self.store.transaction():
            self.engine._invalidate_window(now, "needs_revalidation")
            self.store.set_setting("coverage_gaps", self.store.get_setting("coverage_gaps", 0) + 1)
            self.store.set_setting("last_coverage_gap", {"reason": reason, "at": now})

    def status(self, connected):
        return {**self.engine.status(), "live_discord_connected": connected,
                "coverage_gaps": self.store.get_setting("coverage_gaps", 0),
                "last_coverage_gap": self.store.get_setting("last_coverage_gap"),
                "uncertain_reports": self.store.db.execute(
                    "SELECT count(*) FROM reports WHERE status='uncertain'").fetchone()[0]}

    def command(self, event, message_id, connected):
        """Return a bounded fixed response, or None for unauthorized/duplicate input."""
        if not isinstance(event, CommandRequest):
            raise TypeError("Expected trusted command metadata")
        c = self.config
        if (event.guild_id != c.guild_id or event.channel_id not in c.command_channel_ids
                or not (event.user_id in c.operator_user_ids or set(event.role_ids) & set(c.operator_role_ids))):
            return None
        now = self.engine._now()
        with self.store.transaction():
            if self.store.db.execute("SELECT 1 FROM command_receipts WHERE message_id=?", (message_id,)).fetchone():
                return None
            # Reserve before any command mutation. Crashed/uncertain commands are never replayed.
            self.store.db.execute("INSERT INTO command_receipts VALUES(?,?)", (message_id, now))
            self.store.db.execute("DELETE FROM command_receipts WHERE message_id IN ("
                                  "SELECT message_id FROM command_receipts ORDER BY created_at DESC LIMIT -1 OFFSET 5000)")
        response = handle_command(self.engine, event)
        if not response.get("authorized"):
            return None
        if not response["ok"]:
            # Error identifiers are generated by the code, not copied from message text.
            return "Moderation command: " + response["error"] + ". Use !mod status, pause, resume, incident ID, or explain ID."
        if event.command in ("status", "pause", "resume"):
            status = self.status(connected)
            gap = status["last_coverage_gap"] or {"reason": "none"}
            return (f"Liberdus moderation: {'paused' if status['paused'] else status['mode']}\n"
                    f"Connected: {status['live_discord_connected']} | Coverage: code only\n"
                    f"Messages: {status['message_count']} | Incidents: {status['incident_count']}\n"
                    f"Pending reports: {status['pending_reports']} | Uncertain: {status['uncertain_reports']}\n"
                    f"Coverage resets: {status['coverage_gaps']} | Last: {gap['reason']}\n"
                    "AI calls: 0 | Enforcement: disabled")
        if event.command in ("incident", "explain"):
            data = response["data"]
            # Saved evidence text never becomes outbound instructions, markdown, or mentions.
            return (f"Incident {data['id']} | revision {data['revision']}\n"
                    f"Rule: {data['rule_id']} | State: {data['status']}\n"
                    f"Author ID: {data['author_id']} | Evidence items: {len(data['evidence'])}\n"
                    "Saved code-rule evidence; no AI or enforcement. Reports are snapshots and may be superseded.")
        return "Moderation setting updated. AI and enforcement remain disabled."

    def claim_report(self):
        """Validate current evidence and persist intent before handing a report to I/O."""
        now = self.engine._now()
        with self.store.transaction():
            self.engine._prune(now)
            if (self.config.mode != "report_only" or self.store.get_setting("paused", False)
                    or self.store.get_setting("policy_hash") != self.config.policy_hash):
                return None
            for report in self.store.reports():
                incident = self.store.incident(report["incident_id"])
                p = report["payload"]
                destination = (self.config.command_channel_ids[0] if report["kind"] == "moderator"
                               else self.config.log_channel_id if report["kind"] == "log" and self.store.get_setting("logs_enabled", False)
                               else None)
                valid = (incident is not None and incident["status"] == "open"
                         and incident["revision"] == report["incident_revision"] == p.get("incident_revision")
                         and incident["policy_hash"] == p.get("policy_hash") == self.config.policy_hash
                         and incident["expires_at"] > now
                         and p.get("guild_id") == self.config.guild_id and p.get("channel_id") == destination
                         and destination is not None and destination not in self.config.monitored_channel_ids
                         and p.get("allowed_mentions") == {"parse": [], "users": [], "roles": [], "replied_user": False}
                         and isinstance(p.get("content"), str) and 0 < len(p["content"]) <= 1900)
                if not valid:
                    self.store.db.execute("UPDATE reports SET status='cancelled', updated_at=? WHERE id=?", (now, report["id"]))
                    continue
                self.store.db.execute("UPDATE reports SET status='sending', updated_at=? WHERE id=?", (now, report["id"]))
                self.store.db.execute("INSERT INTO deliveries VALUES(?,NULL,'sending',?)", (report["id"], now))
                return report
        return None

    def finish_report(self, report_id, message_id=None):
        if message_id is not None and not re.fullmatch(r"[1-9][0-9]{0,19}", message_id):
            raise ValueError("Invalid Discord delivery ID")
        outcome = "sent" if message_id is not None else "uncertain"
        with self.store.transaction():
            self.store.db.execute("UPDATE reports SET status=?, updated_at=? WHERE id=? AND status='sending'",
                                  (outcome, self.engine._now(), report_id))
            self.store.db.execute("UPDATE deliveries SET message_id=?, outcome=?, updated_at=? WHERE report_id=?",
                                  (message_id, outcome, self.engine._now(), report_id))


def delivery_nonce(identity):
    # discord.py 2.7.1 sends enforce_nonce=True whenever a nonce is supplied.
    return hashlib.sha256(identity.encode()).hexdigest()[:24]


def parse_command(content, guild_id, channel_id, user_id, roles=()):
    if not isinstance(content, str) or len(content) > 1000:
        return None
    parts = content.strip().split()
    if len(parts) < 2 or parts[0] != "!mod":
        return None
    try:
        return CommandRequest(guild_id, channel_id, user_id, parts[1], tuple(roles), tuple(parts[2:]))
    except ValueError:
        return None
